name: Get Feed

on:
  #schedule:
  #  - cron: "0 */12 * * *" # each 12 hours
  workflow_dispatch
    inputs:
      description: 'Log level'
      required: true
      default: 'debug'
    tags:
      descrition: 'Test scenario tags'
  
jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update Notion Feed
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          curl -o index.js https://raw.githubusercontent.com/bucan3ve/notion-feeder/build/dist/index.js
          node index.js
